kind: Pod
apiVersion: v1
metadata:
  name: debug
  namespace: expense
spec:
  containers:
  - name: debug
    image: 851725509871.dkr.ecr.us-east-1.amazonaws.com/backend:v1.0
    #image: nirmaladevops12/label1.0